export interface Category {
  id: string;
  name: string;
  cards: string[];
}

export const baseCategories: Category[] = [
  {
    id: "animals",
    name: "Animals",
    cards: [
      "Lion",
      "Elephant",
      "Penguin",
      "Dolphin",
      "Kangaroo",
      "Giraffe",
      "Octopus",
      "Owl",
      "Tiger",
      "Shark",
      "Zebra",
      "Panda",
      "Koala",
      "Cheetah",
      "Gorilla",
      "Rhinoceros",
      "Hippopotamus",
      "Crocodile",
      "Flamingo",
      "Peacock",
      "Wolf",
      "Fox",
      "Bear",
      "Raccoon",
      "Squirrel",
      "Rabbit",
      "Deer",
      "Moose",
      "Bat",
      "Bumblebee",
      "Butterfly",
      "Frog",
      "Turtle",
      "Snake",
      "Camel",
      "Llama",
      "Horse",
      "Chicken",
      "Duck",
      "Eagle",
    ],
  },
  {
    id: "movies",
    name: "Movies",
    cards: [
      "Titanic",
      "Jaws",
      "Frozen",
      "Inception",
      "Jurassic Park",
      "The Matrix",
      "Toy Story",
      "Shrek",
      "Rocky",
      "Alien",
      "Avatar",
      "Gladiator",
      "Casablanca",
      "Psycho",
      "Grease",
      "Ghostbusters",
      "Aladdin",
      "Mulan",
      "Tarzan",
      "Cinderella",
      "Moana",
      "Coco",
      "Up",
      "Cars",
      "Finding Nemo",
      "Ratatouille",
      "WALL-E",
      "Brave",
      "The Lion King",
      "The Incredibles",
      "Jumanji",
      "Twister",
      "Speed",
      "The Terminator",
      "Predator",
      "Ghost",
      "Big",
      "Elf",
      "Home Alone",
      "King Kong",
    ],
  },
  {
    id: "occupations",
    name: "Occupations",
    cards: [
      "Firefighter",
      "Dentist",
      "Pilot",
      "Chef",
      "Plumber",
      "Astronaut",
      "Teacher",
      "Electrician",
      "Lawyer",
      "Farmer",
      "Doctor",
      "Nurse",
      "Veterinarian",
      "Police Officer",
      "Judge",
      "Engineer",
      "Architect",
      "Carpenter",
      "Mechanic",
      "Scientist",
      "Photographer",
      "Journalist",
      "Accountant",
      "Librarian",
      "Barber",
      "Baker",
      "Butcher",
      "Tailor",
      "Cashier",
      "Waiter",
      "Bartender",
      "Musician",
      "Actor",
      "Painter",
      "Sculptor",
      "Coach",
      "Referee",
      "Lifeguard",
      "Translator",
      "Programmer",
    ],
  },
  {
    id: "sports",
    name: "Sports",
    cards: [
      "Soccer",
      "Basketball",
      "Tennis",
      "Golf",
      "Swimming",
      "Baseball",
      "Hockey",
      "Boxing",
      "Surfing",
      "Volleyball",
      "Rugby",
      "Bowling",
      "Football",
      "Cricket",
      "Badminton",
      "Table Tennis",
      "Skiing",
      "Snowboarding",
      "Skateboarding",
      "Gymnastics",
      "Wrestling",
      "Fencing",
      "Archery",
      "Rowing",
      "Sailing",
      "Cycling",
      "Track and Field",
      "Weightlifting",
      "Karate",
      "Judo",
      "Taekwondo",
      "Figure Skating",
      "Curling",
      "Lacrosse",
      "Handball",
      "Water Polo",
      "Diving",
      "Triathlon",
      "Marathon Running",
      "Horse Racing",
    ],
  },
  {
    id: "food-and-drink",
    name: "Food & Drink",
    cards: [
      "Pizza",
      "Sushi",
      "Tacos",
      "Ice Cream",
      "Coffee",
      "Pasta",
      "Burger",
      "Pancakes",
      "Curry",
      "Chocolate",
      "Popcorn",
      "Lemonade",
      "Sandwich",
      "Salad",
      "Soup",
      "Steak",
      "Burrito",
      "Nachos",
      "Hot Dog",
      "French Fries",
      "Waffles",
      "Donut",
      "Cupcake",
      "Cookie",
      "Cheesecake",
      "Pretzel",
      "Bacon",
      "Eggs",
      "Cereal",
      "Yogurt",
      "Smoothie",
      "Milkshake",
      "Tea",
      "Hot Chocolate",
      "Soda",
      "Wine",
      "Beer",
      "Ramen",
      "Dumplings",
      "Croissant",
    ],
  },
  {
    id: "fictional-characters",
    name: "Fictional Characters",
    cards: [
      "Batman",
      "Superman",
      "Spider-Man",
      "Harry Potter",
      "Sherlock Holmes",
      "Dracula",
      "Frankenstein's Monster",
      "Cinderella",
      "Robin Hood",
      "Pinocchio",
      "Mickey Mouse",
      "Darth Vader",
      "Peter Pan",
      "Alice in Wonderland",
      "Snow White",
      "Sleeping Beauty",
      "Little Red Riding Hood",
      "Rapunzel",
      "The Big Bad Wolf",
      "Goldilocks",
      "Tinker Bell",
      "Captain Hook",
      "Winnie the Pooh",
      "Bugs Bunny",
      "Donald Duck",
      "SpongeBob SquarePants",
      "Scooby-Doo",
      "Yoda",
      "Tooth Fairy",
      "Santa Claus",
      "Easter Bunny",
      "Paul Bunyan",
      "King Arthur",
      "Merlin",
      "Wonder Woman",
      "The Joker",
      "Iron Man",
      "Captain America",
      "The Hulk",
      "Wolverine",
    ],
  },
  {
    id: "countries",
    name: "Countries",
    cards: [
      "Japan",
      "Brazil",
      "Canada",
      "Egypt",
      "France",
      "Australia",
      "India",
      "Mexico",
      "Italy",
      "Kenya",
      "Germany",
      "Peru",
      "United Kingdom",
      "Spain",
      "Portugal",
      "Greece",
      "Russia",
      "China",
      "South Korea",
      "Thailand",
      "Vietnam",
      "Indonesia",
      "Philippines",
      "New Zealand",
      "Argentina",
      "Chile",
      "Colombia",
      "Cuba",
      "Jamaica",
      "Morocco",
      "Nigeria",
      "South Africa",
      "Ethiopia",
      "Turkey",
      "Israel",
      "Saudi Arabia",
      "Sweden",
      "Norway",
      "Switzerland",
      "Netherlands",
    ],
  },
  {
    id: "musical-instruments",
    name: "Musical Instruments",
    cards: [
      "Guitar",
      "Piano",
      "Violin",
      "Drums",
      "Trumpet",
      "Saxophone",
      "Flute",
      "Cello",
      "Harp",
      "Accordion",
      "Banjo",
      "Xylophone",
      "Clarinet",
      "Trombone",
      "Tuba",
      "French Horn",
      "Oboe",
      "Bassoon",
      "Piccolo",
      "Bagpipes",
      "Ukulele",
      "Mandolin",
      "Sitar",
      "Double Bass",
      "Viola",
      "Organ",
      "Harmonica",
      "Recorder",
      "Bongos",
      "Tambourine",
      "Maracas",
      "Triangle",
      "Cymbals",
      "Gong",
      "Marimba",
      "Synthesizer",
      "Electric Guitar",
      "Bass Guitar",
      "Didgeridoo",
      "Cowbell",
    ],
  },
  {
    id: "household-objects",
    name: "Household Objects",
    cards: [
      "Toaster",
      "Umbrella",
      "Pillow",
      "Mirror",
      "Ladder",
      "Broom",
      "Candle",
      "Backpack",
      "Scissors",
      "Blender",
      "Lamp",
      "Vacuum",
      "Refrigerator",
      "Microwave",
      "Dishwasher",
      "Washing Machine",
      "Iron",
      "Hair Dryer",
      "Toothbrush",
      "Towel",
      "Blanket",
      "Curtains",
      "Rug",
      "Clock",
      "Calendar",
      "Wallet",
      "Keys",
      "Remote Control",
      "Telephone",
      "Television",
      "Couch",
      "Bookshelf",
      "Desk",
      "Chair",
      "Table",
      "Trash Can",
      "Bucket",
      "Mop",
      "Hammer",
      "Screwdriver",
    ],
  },
  {
    id: "video-games",
    name: "Video Games",
    cards: [
      "Mario",
      "Zelda",
      "Minecraft",
      "Tetris",
      "Pac-Man",
      "Pokemon",
      "Fortnite",
      "Sonic",
      "Halo",
      "Overwatch",
      "Chess",
      "Solitaire",
      "Donkey Kong",
      "Kirby",
      "Metroid",
      "Street Fighter",
      "Mortal Kombat",
      "Tomb Raider",
      "Grand Theft Auto",
      "Call of Duty",
      "World of Warcraft",
      "Animal Crossing",
      "Among Us",
      "Roblox",
      "Candy Crush",
      "Angry Birds",
      "Space Invaders",
      "Frogger",
      "Asteroids",
      "Final Fantasy",
      "Resident Evil",
      "Assassin's Creed",
      "FIFA",
      "Madden",
      "Rocket League",
      "Fall Guys",
      "Portal",
      "Half-Life",
      "Doom",
      "Pinball",
    ],
  },
  {
    id: "mythical-creatures",
    name: "Mythical Creatures",
    cards: [
      "Dragon",
      "Unicorn",
      "Mermaid",
      "Phoenix",
      "Griffin",
      "Centaur",
      "Minotaur",
      "Pegasus",
      "Werewolf",
      "Vampire",
      "Zombie",
      "Ghost",
      "Goblin",
      "Troll",
      "Ogre",
      "Elf",
      "Dwarf",
      "Fairy",
      "Gnome",
      "Leprechaun",
      "Genie",
      "Sphinx",
      "Cyclops",
      "Hydra",
      "Kraken",
      "Yeti",
      "Bigfoot",
      "Loch Ness Monster",
      "Banshee",
      "Gargoyle",
      "Chimera",
      "Basilisk",
      "Siren",
      "Nymph",
      "Wizard",
      "Witch",
      "Sorcerer",
      "Demon",
      "Angel",
      "Cupid",
      "Cerberus",
      "Medusa",
      "Gorgon",
      "Harpy",
      "Satyr",
      "Golem",
      "Wraith",
      "Specter",
      "Poltergeist",
      "Shapeshifter",
    ],
  },
  {
    id: "holidays-and-celebrations",
    name: "Holidays & Celebrations",
    cards: [
      "Christmas",
      "Halloween",
      "Thanksgiving",
      "Easter",
      "New Year's Eve",
      "Valentine's Day",
      "Independence Day",
      "Birthday Party",
      "Wedding",
      "Graduation",
      "St. Patrick's Day",
      "Hanukkah",
      "Diwali",
      "Lunar New Year",
      "Cinco de Mayo",
      "Mother's Day",
      "Father's Day",
      "Labor Day",
      "Memorial Day",
      "Veterans Day",
      "April Fools' Day",
      "Groundhog Day",
      "Mardi Gras",
      "Oktoberfest",
      "Carnival",
      "Bonfire Night",
      "Ramadan",
      "Eid al-Fitr",
      "Kwanzaa",
      "Baby Shower",
      "Anniversary",
      "Retirement Party",
      "Housewarming Party",
      "Quinceanera",
      "Bar Mitzvah",
      "Bat Mitzvah",
      "Prom",
      "Homecoming",
      "Reunion",
      "Costume Party",
      "Surprise Party",
      "Pool Party",
      "Block Party",
      "Potluck",
      "Picnic",
      "Bonfire",
      "Fireworks Show",
      "Parade",
      "Talent Show",
      "Award Ceremony",
    ],
  },
  {
    id: "transportation",
    name: "Modes of Transportation",
    cards: [
      "Airplane",
      "Helicopter",
      "Train",
      "Subway",
      "Bicycle",
      "Motorcycle",
      "Scooter",
      "Skateboard",
      "Car",
      "Truck",
      "Bus",
      "Taxi",
      "Ambulance",
      "Fire Truck",
      "Police Car",
      "Tractor",
      "Bulldozer",
      "Crane Truck",
      "Submarine",
      "Sailboat",
      "Canoe",
      "Kayak",
      "Rowboat",
      "Yacht",
      "Cruise Ship",
      "Ferry",
      "Jet Ski",
      "Hot Air Balloon",
      "Rocket",
      "Spaceship",
      "Hoverboard",
      "Segway",
      "Unicycle",
      "Wheelchair",
      "Golf Cart",
      "Snowmobile",
      "Sled",
      "Dog Sled",
      "Horse-Drawn Carriage",
      "Rickshaw",
      "Gondola",
      "Cable Car",
      "Monorail",
      "Tram",
      "Blimp",
      "Glider",
      "Hang Glider",
      "Parachute",
      "Skis",
      "Snowboard",
    ],
  },
  {
    id: "landmarks",
    name: "Famous Landmarks",
    cards: [
      "Eiffel Tower",
      "Statue of Liberty",
      "Great Wall of China",
      "Great Pyramid of Giza",
      "Taj Mahal",
      "Colosseum",
      "Big Ben",
      "Golden Gate Bridge",
      "Mount Rushmore",
      "Stonehenge",
      "Sydney Opera House",
      "Leaning Tower of Pisa",
      "Machu Picchu",
      "Christ the Redeemer",
      "Niagara Falls",
      "Grand Canyon",
      "Mount Everest",
      "Times Square",
      "Empire State Building",
      "Hollywood Sign",
      "Buckingham Palace",
      "Notre-Dame Cathedral",
      "Brandenburg Gate",
      "Acropolis of Athens",
      "Petra",
      "Angkor Wat",
      "Burj Khalifa",
      "CN Tower",
      "Space Needle",
      "Hoover Dam",
      "Mount Fuji",
      "Uluru",
      "Table Mountain",
      "Victoria Falls",
      "Kremlin",
      "Forbidden City",
      "Sagrada Familia",
      "Louvre Pyramid",
      "London Eye",
      "Tower Bridge",
      "Alcatraz",
      "Golden Temple",
      "Blue Mosque",
      "Neuschwanstein Castle",
      "Chichen Itza",
      "Easter Island",
      "Yellowstone",
      "Mount Kilimanjaro",
      "Dead Sea",
      "Amazon Rainforest",
    ],
  },
  {
    id: "board-and-card-games",
    name: "Board Games & Card Games",
    cards: [
      "Chess",
      "Checkers",
      "Monopoly",
      "Scrabble",
      "Poker",
      "Uno",
      "Bingo",
      "Dominoes",
      "Jenga",
      "Clue",
      "Risk",
      "Battleship",
      "Backgammon",
      "Yahtzee",
      "Trivial Pursuit",
      "Charades",
      "Pictionary",
      "Candy Land",
      "Chutes and Ladders",
      "Connect Four",
      "Sorry",
      "The Game of Life",
      "Operation",
      "Twister",
      "Mouse Trap",
      "Rummy",
      "Solitaire",
      "Bridge",
      "Blackjack",
      "Go Fish",
      "War",
      "Euchre",
      "Spades",
      "Hearts",
      "Cribbage",
      "Mahjong",
      "Dungeons and Dragons",
      "Tarot",
      "Old Maid",
      "Memory",
      "Tic-Tac-Toe",
      "Hangman",
      "Dominion",
      "Catan",
      "Pandemic",
      "Codenames",
      "Taboo",
      "Balderdash",
      "Heads Up",
      "Truth or Dare",
    ],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return baseCategories.find((c) => c.id === id);
}
