export interface Category {
  id: string;
  name: string;
  cards: string[];
}

export const baseCategories: Category[] = [
  {
    id: "animals",
    name: "Animals",
    cards: [
      "Lion",
      "Elephant",
      "Penguin",
      "Dolphin",
      "Kangaroo",
      "Giraffe",
      "Octopus",
      "Owl",
      "Tiger",
      "Shark",
    ],
  },
  {
    id: "movies",
    name: "Movies",
    cards: [
      "Titanic",
      "Jaws",
      "Frozen",
      "Inception",
      "Jurassic Park",
      "The Matrix",
      "Toy Story",
      "Shrek",
      "Rocky",
      "Alien",
    ],
  },
  {
    id: "occupations",
    name: "Occupations",
    cards: [
      "Firefighter",
      "Dentist",
      "Pilot",
      "Chef",
      "Plumber",
      "Astronaut",
      "Teacher",
      "Electrician",
      "Lawyer",
      "Farmer",
    ],
  },
  {
    id: "sports",
    name: "Sports",
    cards: [
      "Soccer",
      "Basketball",
      "Tennis",
      "Golf",
      "Swimming",
      "Baseball",
      "Hockey",
      "Boxing",
      "Surfing",
      "Volleyball",
      "Rugby",
      "Bowling",
    ],
  },
  {
    id: "food-and-drink",
    name: "Food & Drink",
    cards: [
      "Pizza",
      "Sushi",
      "Tacos",
      "Ice Cream",
      "Coffee",
      "Pasta",
      "Burger",
      "Pancakes",
      "Curry",
      "Chocolate",
      "Popcorn",
      "Lemonade",
    ],
  },
  {
    id: "fictional-characters",
    name: "Fictional Characters",
    cards: [
      "Batman",
      "Superman",
      "Spider-Man",
      "Harry Potter",
      "Sherlock Holmes",
      "Dracula",
      "Frankenstein's Monster",
      "Cinderella",
      "Robin Hood",
      "Pinocchio",
      "Mickey Mouse",
      "Darth Vader",
    ],
  },
  {
    id: "countries",
    name: "Countries",
    cards: [
      "Japan",
      "Brazil",
      "Canada",
      "Egypt",
      "France",
      "Australia",
      "India",
      "Mexico",
      "Italy",
      "Kenya",
      "Germany",
      "Peru",
    ],
  },
  {
    id: "musical-instruments",
    name: "Musical Instruments",
    cards: [
      "Guitar",
      "Piano",
      "Violin",
      "Drums",
      "Trumpet",
      "Saxophone",
      "Flute",
      "Cello",
      "Harp",
      "Accordion",
      "Banjo",
      "Xylophone",
    ],
  },
  {
    id: "household-objects",
    name: "Household Objects",
    cards: [
      "Toaster",
      "Umbrella",
      "Pillow",
      "Mirror",
      "Ladder",
      "Broom",
      "Candle",
      "Backpack",
      "Scissors",
      "Blender",
      "Lamp",
      "Vacuum",
    ],
  },
  {
    id: "video-games",
    name: "Video Games",
    cards: [
      "Mario",
      "Zelda",
      "Minecraft",
      "Tetris",
      "Pac-Man",
      "Pokemon",
      "Fortnite",
      "Sonic",
      "Halo",
      "Overwatch",
      "Chess",
      "Solitaire",
    ],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return baseCategories.find((c) => c.id === id);
}
