/**
 * Which picker section each base category is listed under, in the order sections are shown.
 * A category missing from here still loads, under FALLBACK_SECTION, with a startup warning.
 */
export const CATEGORY_SECTIONS: Record<string, string[]> = {
  Characters: [
    "cartoon-characters",
    "classic-cartoons",
    "nickelodeon-characters",
    "disney-characters",
    "anime-characters",
    "pokemon-gen-1",
    "superheroes-and-villains",
    "side-characters",
    "movie-villains",
    "video-game-characters",
    "fictional-characters",
    "famous-duos-and-groups",
    "fairy-tales-and-nursery-rhymes",
  ],
  People: [
    "celebrities",
    "hollywood-actors",
    "musicians",
    "music-legends",
    "youtubers-and-streamers",
    "athletes",
    "historical-figures",
    "famous-real-duos",
    "bald-celebrities",
    "bearded-celebrities",
  ],
  History: ["tragic-events", "historical-events"],
  "Pop Culture": [
    "movies",
    "animated-films",
    "tv-shows",
    "video-games",
    "novels",
    "memes-and-viral-moments",
    "90s-toys",
    "retro-tech",
    "brands",
    "apps-and-websites",
    "toys",
    "board-games",
    "board-and-card-games",
  ],
  "Myth & Fantasy": [
    "cryptids",
    "mythical-creatures",
    "superpowers-and-abilities",
    "medieval-and-fantasy",
    "pirates-and-seafaring",
    "wild-west-and-cowboys",
  ],
  "Animals & Nature": [
    "animals",
    "mammals",
    "birds",
    "fish-and-sea-life",
    "reptiles-and-amphibians",
    "insects-and-bugs",
    "dinosaurs",
    "plants-and-flowers",
    "weather-and-nature",
  ],
  "Food & Drink": [
    "food-and-drink",
    "fruits",
    "vegetables",
    "snacks-and-candy",
    "desserts-and-sweets",
    "breakfast-foods",
    "drinks",
    "fast-food-and-restaurant-meals",
    "pizza-and-toppings",
    "ice-cream-and-frozen-treats",
  ],
  "Everyday Things": [
    "household-objects",
    "kitchen-tools",
    "tools",
    "clothing",
    "transportation",
    "musical-instruments",
    "sports",
    "sports-equipment-and-gear",
    "occupations",
    "hobbies-and-activities",
    "dances-and-moves",
    "school-subjects-and-science",
    "school-supplies",
    "office-and-work",
    "bathroom-and-bedroom",
  ],
  "Places & Occasions": [
    "countries",
    "landmarks",
    "holidays-and-celebrations",
    "christmas-and-winter",
    "halloween",
    "at-the-airport",
    "at-the-beach",
    "at-the-circus-and-fair",
    "at-the-hospital",
    "camping-and-outdoors",
    "farm-and-countryside",
    "garden-and-yard",
    "in-the-city",
  ],
};

export const FALLBACK_SECTION = "More";
